import slugify from 'slugify'

export default function normalizeString(string) {
    const sanitized = string
        .toLowerCase()
        .replace('mister', 'mr')
        .replace("i'm", 'i am')
        .replace("let's", 'let us')
        .replace("you're", 'you are')
        .replace("that's", 'that is')
        .replace("he's", 'he is')
        .replace("it's", 'it is')
        .replace("she's", 'she is')
        .replace("we're", 'we are')
        .replace("we'r", 'we are')
        .replace("they're", 'they are')
        .replace("they'r", 'they are')
        .replace("i'll", 'i will')
        .replace("i'l", 'i will')
        .replace("we'll", 'we will')
        .replace("we'l", 'we will')
        .replace("you'll", 'you will')
        .replace("you'l", 'you will')
        .replace("it'll", 'it will')
        .replace("it'l", 'it will')
        .replace("he'll", 'he will')
        .replace("he'l", 'he will')
        .replace("y'all", 'you all')
        .replace("y'al", 'you all')
        .replace("she'll", 'she will')
        .replace("she'l", 'she will')
        .replace("i've", 'i have')
        .replace("i'v", 'i have')
        .replace("should've", 'should have')
        .replace("should'v", 'should have')
        .replace("you've", 'you have')
        .replace("you'v", 'you have')
        .replace("could've", 'could have')
        .replace("could'v", 'could have')
        .replace("they've", 'they have')
        .replace("they'v", 'they have')
        .replace("i'd", 'i would')
        .replace("we've", 'we have')
        .replace("we'v", 'we have')
        .replace("they'd", 'they would')
        .replace("you'd", 'you would')
        .replace("we'd", 'we would')
        .replace("he'd", 'he would')
        .replace("she'd", 'she would')
        .replace("didn't", 'did not')
        .replace("don't", 'do not')
        .replace("doesn't", 'does not')
        .replace('doesn', 'does not')
        .replace("can't", 'can not')
        .replace('cannot', 'can not')
        .replace("isn't", 'is not')
        .replace('isn', 'is not')
        .replace("aren't", 'are not')
        .replace('aren', 'are not')
        .replace("shouldn't", 'should not')
        .replace('shouldn', 'should not')
        .replace("couldn't", 'could not')
        .replace('couldn', 'could not')
        .replace("wouldn't", 'would not')
        .replace('wouldn', 'would not')
        .replace("hasn't", 'has not')
        .replace('hasn', 'has not')
        .replace("wasn't", 'was not')
        .replace('wasn', 'was not')
        .replace("won't", 'will not')
        .replace("weren't", 'were not')
        .replace('weren', 'were not')
        .replace('there is', "there's")
        .replace('there are', "there's")
        .replace('here is', "here's")
        .replace('here are', "here's")

    return slugify(sanitized, {
        lower: true,
        remove: /[*+~.()'"!:@]/g,
    })
}
